---
name: "📕 Documentation issue or suggestion"
description: Report an issue or a suggestion for documentation
title: "(Short description)"
labels: [documentation]
assignees: [NelsonBN]



body:
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: A clear and concise description of the issue.
    validations:
      required: true


  - type: textarea
    id: links
    attributes:
      label: Links
      description: Include links to affected documentation page(s).
    validations:
      required: true