name: 'Check Markdown links'


on:
  workflow_dispatch:

  # Schedule to run every week on Sunday at 00:00 UTC
  schedule:
    - cron: '0 0 * * 0'

  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - main


jobs:
  markdown-link-check:
    name: "Markdown link check"
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v5.0.0

    - name: 'Readme analysis'
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: 'yes'
        base-branch: 'main'
        config-file: '.github/workflows/markdown-link-check.json'
